title: "Dennis Vidal's Portfolio"
name: "Dennis Vidal"
email: "Dennis.Vidal.dc@gmail.com"
resume: "/resume/DennisVidal_Resume.pdf"

permalink: "pretty"

defaults:
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      permalink: "/:title"